// Generated by cormid Studio. Edit in the local dashboard.
export const siteConfig = {
  "title": "cormid の 小窝",
  "faviconUrl": "/media/76e0e2bda1b59016e796-icon.png",
  "authorName": "cormid",
  "bio": "把生活的碎片、学习的足迹，和喜欢的事物，慢慢收藏在这里。",
  "navTitle": "cormid",
  "navSuffix": "の",
  "navAfter": "小窝",
  "avatarUrl": "/media/76e0e2bda1b59016e796.webp",
  "useGradient": false,
  "themeColors": [
    "#a18cd1",
    "#fbc2eb",
    "#a1c4fd",
    "#c2e9fb"
  ],
  "bgImages": [
    "/media/bb29272608a19420d584-poster.webp"
  ],
  "defaultPostCover": "/media/bb29272608a19420d584-poster.webp",
  "photoWallImage": "/media/bb29272608a19420d584-poster.webp",
  "cloudMusicIds": [],
  "social": {
    "github": "https://github.com/Kirtofu",
    "gitee": "",
    "google": "",
    "email": "",
    "qq": "",
    "wechat": ""
  },
  "counts": {
    "photos": 0
  },
  "chatterTitle": "云端杂谈",
  "chatterDescription": "偶尔停下来，收藏一点生活里的闪光。",
  "danmakuList": [
    "今天也有好好生活",
    "欢迎来到 cormid 的小窝",
    "收藏一点星光",
    "慢慢来，也没关系"
  ],
  "gitalkConfig": {
    "clientID": "",
    "clientSecret": "",
    "repo": "",
    "owner": "",
    "admin": []
  },
  "buildDate": "2026-10-05T12:00:00+08:00",
  "footerBadges": [] as {name:string;color:string;svg:string}[],
  "icpConfig": {
    "name": "",
    "link": ""
  },
  "geminiConfig": {
    "modelId": "",
    "systemPrompt": "",
    "maxOutputTokens": 150,
    "temperature": 0.85
  },
  "friendLinkApplyFormat": "名称：cormid の 小窝\n简介：收藏生活、学习和喜欢的事物\n链接：https://kirtofu.github.io/\n头像：https://kirtofu.github.io/media/76e0e2bda1b59016e796.webp",
  "enableLevelSystem": false,
  "backgroundMode": "video",
  "bgVideoUrl": "/media/bb29272608a19420d584.mp4",
  "bgVideoPoster": "/media/bb29272608a19420d584-poster.webp",
  "backgroundBlur": 3,
  "backgroundOverlayOpacity": 35
};
